import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-[100vw] h-[100vh] flex items-center justify-center">
        <Link
          href={`https://www.facebook.com/v15.0/dialog/oauth?client_id=482223187415893&redirect_uri=https://instagram-web-green.vercel.app/&state=bismvrckz`}
        >
          <button>Sign in with facebook</button>
        </Link>
      </div>
    </>
  );
}
